spring:

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 5000

#server config
server:
  port: 8088

#eureka congig
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

#custom congig
custom:
  UserServiceTopicName: userServiceEvents
  intervalForAttempt: 50
  maxAttempts: 3





