spring:

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 5000

#server config
server:
  port: 8088

#eureka congig

#custom congig





